CREATE TABLE clients (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR (50) NOT NULL,
  surname VARCHAR (50) NOT NULL,
  email VARCHAR (50) NOT NULL,
  phone VARCHAR (50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE masters (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR (50) NOT NULL,
  surname VARCHAR (50) NOT NULL,
  email VARCHAR (50) NOT NULL,
  phone VARCHAR (50) NOT NULL,
  nickname VARCHAR (50) NOT NULL,
  PRIMARY KEY (id)
);
